### ISSUE TITLE
Templates from repo cause exception when following video

### ISSUE THREAD

**Issue by kenlacrosse** [talkpython/modern-apis-with-fastapi#18]
![image](https://github.com/user-attachments/assets/aa8419a7-1bda-4b61-9b22-bc4acc717fa1)
Chapter 5/9:Rendering HTML Templates[v3/14] causes exceptions when using templates from repo.  See below:

C:\TFS\Development\FastAPI\realisticAPI\.venv\Scripts\python.exe C:\TFS\Development\FastAPI\realisticAPI\main.py 
INFO:     Started server process [23960]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:53674 - "GET / HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\fastapi\routing.py", line 214, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\starlette\concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TFS\Development\FastAPI\realisticAPI\main.py", line 11, in index
    return templates.TemplateResponse('index.htma', {'request': request})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\starlette\templating.py", line 208, in TemplateResponse
    template = self.get_template(name)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\starlette\templating.py", line 131, in get_template
    return self.env.get_template(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\TFS\Development\FastAPI\realisticAPI\.venv\Lib\site-packages\jinja2\loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: index.htma
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [23960]

Process finished with exit code 0

**Comment by kenlacrosse** [comment]
Initial problem is existence of subfolders but removal of subfolders and references to subfolders in templates does not resolve the issue.

**Comment by mikeckennedy** [comment]
Hi @kenlacrosse 

Looking at the error, it seems a file **index.htma** is the problem: `TemplateNotFound: index.htma`

Is there really code in the repo looking for index.htm**a** or was that a typo in your code?

**Comment by kenlacrosse** [comment]
Nope, my fumble fingers foiled me again!
